//
// Created by root on 7/26/16.
//

#ifndef MULTIPARTYPSI_SIMPLEHASHINGPOLYNOMIALLEADER_H
#define MULTIPARTYPSI_SIMPLEHASHINGPOLYNOMIALLEADER_H


class SimpleHashingPolynomialLeader {

};


#endif //MULTIPARTYPSI_SIMPLEHASHINGPOLYNOMIALLEADER_H
